### ISSUE TITLE
SAS doesn't decode all Server-Assignment-Types

### ISSUE THREAD

**Issue by mirw** [Metaswitch/clearwater-sas-resources#64]
I had a Server-Assignment-Request with a Server-Assignment-Type of DEREG_AUTH_TIMEOUT.  SAS didn't crack it out correctly:

    000001b8  [ Server-Assignment-Type = 0000000a ]

**Comment by rkd-msw** [comment]
I looked at this and emailed @AlexHockey about a potential fix.

**Comment by rkd-msw** [comment]
This wasn't a Clearwater issue, but I've fixed it in SAS and applied that fix to Dogfood:

0000013c  [ Server-Name = "sip:sprout-site1.rkd.cw-ngv.com" ]
00000168  [ Server-Assignment-Type = AUTHENTICATION_TIMEOUT ]
00000178  [ User-Data-Already-Available = USER_DATA_NOT_AVAILABLE ]
